//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ProjetStage {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSetRensein")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSetRensein : global::System.Data.DataSet {
        
        private Fiche_RenseignementDataTable tableFiche_Renseignement;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public DataSetRensein() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected DataSetRensein(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Fiche_Renseignement"] != null)) {
                    base.Tables.Add(new Fiche_RenseignementDataTable(ds.Tables["Fiche_Renseignement"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Fiche_RenseignementDataTable Fiche_Renseignement {
            get {
                return this.tableFiche_Renseignement;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataSetRensein cln = ((DataSetRensein)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Fiche_Renseignement"] != null)) {
                    base.Tables.Add(new Fiche_RenseignementDataTable(ds.Tables["Fiche_Renseignement"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableFiche_Renseignement = ((Fiche_RenseignementDataTable)(base.Tables["Fiche_Renseignement"]));
            if ((initTable == true)) {
                if ((this.tableFiche_Renseignement != null)) {
                    this.tableFiche_Renseignement.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataSetRensein";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSetRensein.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableFiche_Renseignement = new Fiche_RenseignementDataTable();
            base.Tables.Add(this.tableFiche_Renseignement);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeFiche_Renseignement() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSetRensein ds = new DataSetRensein();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void Fiche_RenseignementRowChangeEventHandler(object sender, Fiche_RenseignementRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Fiche_RenseignementDataTable : global::System.Data.TypedTableBase<Fiche_RenseignementRow> {
            
            private global::System.Data.DataColumn columnPPR;
            
            private global::System.Data.DataColumn columnNOMFR;
            
            private global::System.Data.DataColumn columnPRENOMFR;
            
            private global::System.Data.DataColumn columnNomAr;
            
            private global::System.Data.DataColumn columnPrenomAr;
            
            private global::System.Data.DataColumn columnCIN;
            
            private global::System.Data.DataColumn columnADRESSEFR;
            
            private global::System.Data.DataColumn columnFONCTIONFR;
            
            private global::System.Data.DataColumn columnSEXE;
            
            private global::System.Data.DataColumn columnCIVILITE;
            
            private global::System.Data.DataColumn columnLibelleGradeFr;
            
            private global::System.Data.DataColumn columnCadreFR;
            
            private global::System.Data.DataColumn columnLibelleSpecialiteFR;
            
            private global::System.Data.DataColumn columnDate_Naissance;
            
            private global::System.Data.DataColumn columnDate_Recrutement;
            
            private global::System.Data.DataColumn columnDate_Affectation;
            
            private global::System.Data.DataColumn columnLibelleFSFR;
            
            private global::System.Data.DataColumn columnLibelleAffectationFR;
            
            private global::System.Data.DataColumn columnLibelleEntiteFR;
            
            private global::System.Data.DataColumn columnSITUATION_FAMILIALE;
            
            private global::System.Data.DataColumn columnNOMBRE_ENFANTS;
            
            private global::System.Data.DataColumn columnTELEPHONE;
            
            private global::System.Data.DataColumn columnPhoto;
            
            private global::System.Data.DataColumn columnConjoint;
            
            private global::System.Data.DataColumn columnFonctionConj;
            
            private global::System.Data.DataColumn columnVilleAffectConjoint;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementDataTable() {
                this.TableName = "Fiche_Renseignement";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal Fiche_RenseignementDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected Fiche_RenseignementDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PPRColumn {
                get {
                    return this.columnPPR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NOMFRColumn {
                get {
                    return this.columnNOMFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PRENOMFRColumn {
                get {
                    return this.columnPRENOMFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NomArColumn {
                get {
                    return this.columnNomAr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PrenomArColumn {
                get {
                    return this.columnPrenomAr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CINColumn {
                get {
                    return this.columnCIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ADRESSEFRColumn {
                get {
                    return this.columnADRESSEFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FONCTIONFRColumn {
                get {
                    return this.columnFONCTIONFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SEXEColumn {
                get {
                    return this.columnSEXE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CIVILITEColumn {
                get {
                    return this.columnCIVILITE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LibelleGradeFrColumn {
                get {
                    return this.columnLibelleGradeFr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CadreFRColumn {
                get {
                    return this.columnCadreFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LibelleSpecialiteFRColumn {
                get {
                    return this.columnLibelleSpecialiteFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Date_NaissanceColumn {
                get {
                    return this.columnDate_Naissance;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Date_RecrutementColumn {
                get {
                    return this.columnDate_Recrutement;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Date_AffectationColumn {
                get {
                    return this.columnDate_Affectation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LibelleFSFRColumn {
                get {
                    return this.columnLibelleFSFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LibelleAffectationFRColumn {
                get {
                    return this.columnLibelleAffectationFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LibelleEntiteFRColumn {
                get {
                    return this.columnLibelleEntiteFR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SITUATION_FAMILIALEColumn {
                get {
                    return this.columnSITUATION_FAMILIALE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NOMBRE_ENFANTSColumn {
                get {
                    return this.columnNOMBRE_ENFANTS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TELEPHONEColumn {
                get {
                    return this.columnTELEPHONE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PhotoColumn {
                get {
                    return this.columnPhoto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ConjointColumn {
                get {
                    return this.columnConjoint;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn FonctionConjColumn {
                get {
                    return this.columnFonctionConj;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn VilleAffectConjointColumn {
                get {
                    return this.columnVilleAffectConjoint;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementRow this[int index] {
                get {
                    return ((Fiche_RenseignementRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event Fiche_RenseignementRowChangeEventHandler Fiche_RenseignementRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event Fiche_RenseignementRowChangeEventHandler Fiche_RenseignementRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event Fiche_RenseignementRowChangeEventHandler Fiche_RenseignementRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event Fiche_RenseignementRowChangeEventHandler Fiche_RenseignementRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddFiche_RenseignementRow(Fiche_RenseignementRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementRow AddFiche_RenseignementRow(
                        int PPR, 
                        string NOMFR, 
                        string PRENOMFR, 
                        string NomAr, 
                        string PrenomAr, 
                        string CIN, 
                        string ADRESSEFR, 
                        string FONCTIONFR, 
                        string SEXE, 
                        string CIVILITE, 
                        string LibelleGradeFr, 
                        string CadreFR, 
                        string LibelleSpecialiteFR, 
                        System.DateTime Date_Naissance, 
                        System.DateTime Date_Recrutement, 
                        System.DateTime Date_Affectation, 
                        string LibelleFSFR, 
                        string LibelleAffectationFR, 
                        string LibelleEntiteFR, 
                        string SITUATION_FAMILIALE, 
                        int NOMBRE_ENFANTS, 
                        string TELEPHONE, 
                        byte[] Photo, 
                        string Conjoint, 
                        string FonctionConj, 
                        string VilleAffectConjoint) {
                Fiche_RenseignementRow rowFiche_RenseignementRow = ((Fiche_RenseignementRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        PPR,
                        NOMFR,
                        PRENOMFR,
                        NomAr,
                        PrenomAr,
                        CIN,
                        ADRESSEFR,
                        FONCTIONFR,
                        SEXE,
                        CIVILITE,
                        LibelleGradeFr,
                        CadreFR,
                        LibelleSpecialiteFR,
                        Date_Naissance,
                        Date_Recrutement,
                        Date_Affectation,
                        LibelleFSFR,
                        LibelleAffectationFR,
                        LibelleEntiteFR,
                        SITUATION_FAMILIALE,
                        NOMBRE_ENFANTS,
                        TELEPHONE,
                        Photo,
                        Conjoint,
                        FonctionConj,
                        VilleAffectConjoint};
                rowFiche_RenseignementRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowFiche_RenseignementRow);
                return rowFiche_RenseignementRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementRow FindByPPR(int PPR) {
                return ((Fiche_RenseignementRow)(this.Rows.Find(new object[] {
                            PPR})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                Fiche_RenseignementDataTable cln = ((Fiche_RenseignementDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Fiche_RenseignementDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnPPR = base.Columns["PPR"];
                this.columnNOMFR = base.Columns["NOMFR"];
                this.columnPRENOMFR = base.Columns["PRENOMFR"];
                this.columnNomAr = base.Columns["NomAr"];
                this.columnPrenomAr = base.Columns["PrenomAr"];
                this.columnCIN = base.Columns["CIN"];
                this.columnADRESSEFR = base.Columns["ADRESSEFR"];
                this.columnFONCTIONFR = base.Columns["FONCTIONFR"];
                this.columnSEXE = base.Columns["SEXE"];
                this.columnCIVILITE = base.Columns["CIVILITE"];
                this.columnLibelleGradeFr = base.Columns["LibelleGradeFr"];
                this.columnCadreFR = base.Columns["CadreFR"];
                this.columnLibelleSpecialiteFR = base.Columns["LibelleSpecialiteFR"];
                this.columnDate_Naissance = base.Columns["Date_Naissance"];
                this.columnDate_Recrutement = base.Columns["Date_Recrutement"];
                this.columnDate_Affectation = base.Columns["Date_Affectation"];
                this.columnLibelleFSFR = base.Columns["LibelleFSFR"];
                this.columnLibelleAffectationFR = base.Columns["LibelleAffectationFR"];
                this.columnLibelleEntiteFR = base.Columns["LibelleEntiteFR"];
                this.columnSITUATION_FAMILIALE = base.Columns["SITUATION_FAMILIALE"];
                this.columnNOMBRE_ENFANTS = base.Columns["NOMBRE_ENFANTS"];
                this.columnTELEPHONE = base.Columns["TELEPHONE"];
                this.columnPhoto = base.Columns["Photo"];
                this.columnConjoint = base.Columns["Conjoint"];
                this.columnFonctionConj = base.Columns["FonctionConj"];
                this.columnVilleAffectConjoint = base.Columns["VilleAffectConjoint"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnPPR = new global::System.Data.DataColumn("PPR", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPPR);
                this.columnNOMFR = new global::System.Data.DataColumn("NOMFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOMFR);
                this.columnPRENOMFR = new global::System.Data.DataColumn("PRENOMFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRENOMFR);
                this.columnNomAr = new global::System.Data.DataColumn("NomAr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomAr);
                this.columnPrenomAr = new global::System.Data.DataColumn("PrenomAr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrenomAr);
                this.columnCIN = new global::System.Data.DataColumn("CIN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCIN);
                this.columnADRESSEFR = new global::System.Data.DataColumn("ADRESSEFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnADRESSEFR);
                this.columnFONCTIONFR = new global::System.Data.DataColumn("FONCTIONFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFONCTIONFR);
                this.columnSEXE = new global::System.Data.DataColumn("SEXE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSEXE);
                this.columnCIVILITE = new global::System.Data.DataColumn("CIVILITE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCIVILITE);
                this.columnLibelleGradeFr = new global::System.Data.DataColumn("LibelleGradeFr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLibelleGradeFr);
                this.columnCadreFR = new global::System.Data.DataColumn("CadreFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCadreFR);
                this.columnLibelleSpecialiteFR = new global::System.Data.DataColumn("LibelleSpecialiteFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLibelleSpecialiteFR);
                this.columnDate_Naissance = new global::System.Data.DataColumn("Date_Naissance", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDate_Naissance);
                this.columnDate_Recrutement = new global::System.Data.DataColumn("Date_Recrutement", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDate_Recrutement);
                this.columnDate_Affectation = new global::System.Data.DataColumn("Date_Affectation", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDate_Affectation);
                this.columnLibelleFSFR = new global::System.Data.DataColumn("LibelleFSFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLibelleFSFR);
                this.columnLibelleAffectationFR = new global::System.Data.DataColumn("LibelleAffectationFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLibelleAffectationFR);
                this.columnLibelleEntiteFR = new global::System.Data.DataColumn("LibelleEntiteFR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLibelleEntiteFR);
                this.columnSITUATION_FAMILIALE = new global::System.Data.DataColumn("SITUATION_FAMILIALE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSITUATION_FAMILIALE);
                this.columnNOMBRE_ENFANTS = new global::System.Data.DataColumn("NOMBRE_ENFANTS", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOMBRE_ENFANTS);
                this.columnTELEPHONE = new global::System.Data.DataColumn("TELEPHONE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTELEPHONE);
                this.columnPhoto = new global::System.Data.DataColumn("Photo", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPhoto);
                this.columnConjoint = new global::System.Data.DataColumn("Conjoint", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnConjoint);
                this.columnFonctionConj = new global::System.Data.DataColumn("FonctionConj", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFonctionConj);
                this.columnVilleAffectConjoint = new global::System.Data.DataColumn("VilleAffectConjoint", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVilleAffectConjoint);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnPPR}, true));
                this.columnPPR.AllowDBNull = false;
                this.columnPPR.Unique = true;
                this.columnNOMFR.MaxLength = 260;
                this.columnPRENOMFR.MaxLength = 260;
                this.columnNomAr.MaxLength = 250;
                this.columnPrenomAr.MaxLength = 250;
                this.columnCIN.MaxLength = 260;
                this.columnADRESSEFR.MaxLength = 260;
                this.columnFONCTIONFR.MaxLength = 260;
                this.columnSEXE.MaxLength = 1;
                this.columnCIVILITE.MaxLength = 50;
                this.columnLibelleGradeFr.MaxLength = 250;
                this.columnCadreFR.MaxLength = 50;
                this.columnLibelleSpecialiteFR.MaxLength = 250;
                this.columnLibelleFSFR.MaxLength = 250;
                this.columnLibelleAffectationFR.MaxLength = 250;
                this.columnLibelleEntiteFR.MaxLength = 50;
                this.columnSITUATION_FAMILIALE.MaxLength = 260;
                this.columnTELEPHONE.MaxLength = 260;
                this.columnConjoint.MaxLength = 260;
                this.columnFonctionConj.MaxLength = 260;
                this.columnVilleAffectConjoint.MaxLength = 260;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementRow NewFiche_RenseignementRow() {
                return ((Fiche_RenseignementRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Fiche_RenseignementRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(Fiche_RenseignementRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Fiche_RenseignementRowChanged != null)) {
                    this.Fiche_RenseignementRowChanged(this, new Fiche_RenseignementRowChangeEvent(((Fiche_RenseignementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Fiche_RenseignementRowChanging != null)) {
                    this.Fiche_RenseignementRowChanging(this, new Fiche_RenseignementRowChangeEvent(((Fiche_RenseignementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Fiche_RenseignementRowDeleted != null)) {
                    this.Fiche_RenseignementRowDeleted(this, new Fiche_RenseignementRowChangeEvent(((Fiche_RenseignementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Fiche_RenseignementRowDeleting != null)) {
                    this.Fiche_RenseignementRowDeleting(this, new Fiche_RenseignementRowChangeEvent(((Fiche_RenseignementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveFiche_RenseignementRow(Fiche_RenseignementRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetRensein ds = new DataSetRensein();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Fiche_RenseignementDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class Fiche_RenseignementRow : global::System.Data.DataRow {
            
            private Fiche_RenseignementDataTable tableFiche_Renseignement;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal Fiche_RenseignementRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableFiche_Renseignement = ((Fiche_RenseignementDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int PPR {
                get {
                    return ((int)(this[this.tableFiche_Renseignement.PPRColumn]));
                }
                set {
                    this[this.tableFiche_Renseignement.PPRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string NOMFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.NOMFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NOMFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.NOMFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PRENOMFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.PRENOMFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PRENOMFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.PRENOMFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string NomAr {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.NomArColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomAr\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.NomArColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PrenomAr {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.PrenomArColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrenomAr\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.PrenomArColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CIN {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.CINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CIN\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.CINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ADRESSEFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.ADRESSEFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ADRESSEFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.ADRESSEFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FONCTIONFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.FONCTIONFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FONCTIONFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.FONCTIONFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SEXE {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.SEXEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SEXE\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.SEXEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CIVILITE {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.CIVILITEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CIVILITE\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.CIVILITEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LibelleGradeFr {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.LibelleGradeFrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LibelleGradeFr\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.LibelleGradeFrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CadreFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.CadreFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CadreFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.CadreFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LibelleSpecialiteFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.LibelleSpecialiteFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LibelleSpecialiteFR\' in table \'Fiche_Renseignement\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.LibelleSpecialiteFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime Date_Naissance {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableFiche_Renseignement.Date_NaissanceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Date_Naissance\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.Date_NaissanceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime Date_Recrutement {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableFiche_Renseignement.Date_RecrutementColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Date_Recrutement\' in table \'Fiche_Renseignement\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.Date_RecrutementColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public System.DateTime Date_Affectation {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableFiche_Renseignement.Date_AffectationColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Date_Affectation\' in table \'Fiche_Renseignement\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.Date_AffectationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LibelleFSFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.LibelleFSFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LibelleFSFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.LibelleFSFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LibelleAffectationFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.LibelleAffectationFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LibelleAffectationFR\' in table \'Fiche_Renseignement\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.LibelleAffectationFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LibelleEntiteFR {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.LibelleEntiteFRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LibelleEntiteFR\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.LibelleEntiteFRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SITUATION_FAMILIALE {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.SITUATION_FAMILIALEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SITUATION_FAMILIALE\' in table \'Fiche_Renseignement\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.SITUATION_FAMILIALEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public int NOMBRE_ENFANTS {
                get {
                    try {
                        return ((int)(this[this.tableFiche_Renseignement.NOMBRE_ENFANTSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NOMBRE_ENFANTS\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.NOMBRE_ENFANTSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TELEPHONE {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.TELEPHONEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TELEPHONE\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.TELEPHONEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public byte[] Photo {
                get {
                    try {
                        return ((byte[])(this[this.tableFiche_Renseignement.PhotoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Photo\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.PhotoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Conjoint {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.ConjointColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Conjoint\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.ConjointColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string FonctionConj {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.FonctionConjColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FonctionConj\' in table \'Fiche_Renseignement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.FonctionConjColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string VilleAffectConjoint {
                get {
                    try {
                        return ((string)(this[this.tableFiche_Renseignement.VilleAffectConjointColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'VilleAffectConjoint\' in table \'Fiche_Renseignement\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableFiche_Renseignement.VilleAffectConjointColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNOMFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.NOMFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNOMFRNull() {
                this[this.tableFiche_Renseignement.NOMFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPRENOMFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.PRENOMFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPRENOMFRNull() {
                this[this.tableFiche_Renseignement.PRENOMFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNomArNull() {
                return this.IsNull(this.tableFiche_Renseignement.NomArColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNomArNull() {
                this[this.tableFiche_Renseignement.NomArColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPrenomArNull() {
                return this.IsNull(this.tableFiche_Renseignement.PrenomArColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPrenomArNull() {
                this[this.tableFiche_Renseignement.PrenomArColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCINNull() {
                return this.IsNull(this.tableFiche_Renseignement.CINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCINNull() {
                this[this.tableFiche_Renseignement.CINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsADRESSEFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.ADRESSEFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetADRESSEFRNull() {
                this[this.tableFiche_Renseignement.ADRESSEFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFONCTIONFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.FONCTIONFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFONCTIONFRNull() {
                this[this.tableFiche_Renseignement.FONCTIONFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSEXENull() {
                return this.IsNull(this.tableFiche_Renseignement.SEXEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSEXENull() {
                this[this.tableFiche_Renseignement.SEXEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCIVILITENull() {
                return this.IsNull(this.tableFiche_Renseignement.CIVILITEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCIVILITENull() {
                this[this.tableFiche_Renseignement.CIVILITEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLibelleGradeFrNull() {
                return this.IsNull(this.tableFiche_Renseignement.LibelleGradeFrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLibelleGradeFrNull() {
                this[this.tableFiche_Renseignement.LibelleGradeFrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCadreFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.CadreFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCadreFRNull() {
                this[this.tableFiche_Renseignement.CadreFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLibelleSpecialiteFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.LibelleSpecialiteFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLibelleSpecialiteFRNull() {
                this[this.tableFiche_Renseignement.LibelleSpecialiteFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDate_NaissanceNull() {
                return this.IsNull(this.tableFiche_Renseignement.Date_NaissanceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDate_NaissanceNull() {
                this[this.tableFiche_Renseignement.Date_NaissanceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDate_RecrutementNull() {
                return this.IsNull(this.tableFiche_Renseignement.Date_RecrutementColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDate_RecrutementNull() {
                this[this.tableFiche_Renseignement.Date_RecrutementColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDate_AffectationNull() {
                return this.IsNull(this.tableFiche_Renseignement.Date_AffectationColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDate_AffectationNull() {
                this[this.tableFiche_Renseignement.Date_AffectationColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLibelleFSFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.LibelleFSFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLibelleFSFRNull() {
                this[this.tableFiche_Renseignement.LibelleFSFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLibelleAffectationFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.LibelleAffectationFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLibelleAffectationFRNull() {
                this[this.tableFiche_Renseignement.LibelleAffectationFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLibelleEntiteFRNull() {
                return this.IsNull(this.tableFiche_Renseignement.LibelleEntiteFRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLibelleEntiteFRNull() {
                this[this.tableFiche_Renseignement.LibelleEntiteFRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSITUATION_FAMILIALENull() {
                return this.IsNull(this.tableFiche_Renseignement.SITUATION_FAMILIALEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSITUATION_FAMILIALENull() {
                this[this.tableFiche_Renseignement.SITUATION_FAMILIALEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNOMBRE_ENFANTSNull() {
                return this.IsNull(this.tableFiche_Renseignement.NOMBRE_ENFANTSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNOMBRE_ENFANTSNull() {
                this[this.tableFiche_Renseignement.NOMBRE_ENFANTSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTELEPHONENull() {
                return this.IsNull(this.tableFiche_Renseignement.TELEPHONEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTELEPHONENull() {
                this[this.tableFiche_Renseignement.TELEPHONEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPhotoNull() {
                return this.IsNull(this.tableFiche_Renseignement.PhotoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPhotoNull() {
                this[this.tableFiche_Renseignement.PhotoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsConjointNull() {
                return this.IsNull(this.tableFiche_Renseignement.ConjointColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetConjointNull() {
                this[this.tableFiche_Renseignement.ConjointColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsFonctionConjNull() {
                return this.IsNull(this.tableFiche_Renseignement.FonctionConjColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetFonctionConjNull() {
                this[this.tableFiche_Renseignement.FonctionConjColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsVilleAffectConjointNull() {
                return this.IsNull(this.tableFiche_Renseignement.VilleAffectConjointColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetVilleAffectConjointNull() {
                this[this.tableFiche_Renseignement.VilleAffectConjointColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class Fiche_RenseignementRowChangeEvent : global::System.EventArgs {
            
            private Fiche_RenseignementRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementRowChangeEvent(Fiche_RenseignementRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public Fiche_RenseignementRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591